package com.redhat.batigerteam.compensation_example;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ValidityCheck implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ValidityCheck() {
    }

    public boolean doCheck() {
        return false;
    }


}